name: Build windows zip

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.44.0"

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v6

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' app/pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies (app)
        working-directory: app
        run: flutter pub get

      - name: Dependencies (cargokit - rust_builder)
        working-directory: app/rust_builder/cargokit/build_tool
        run: flutter pub get

      - name: Analyze (app)
        working-directory: app
        run: flutter analyze

      - name: Test (app)
        working-directory: app
        run: flutter test

      - name: Dependencies (common)
        working-directory: common
        run: dart pub get

      - name: Analyze (common)
        working-directory: common
        run: dart analyze

      - name: Test (common)
        working-directory: common
        run: dart test

  build_windows_zip:
    needs:
      - build
      - test
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_architecture: x64
            artifact_architecture: x86-64
            flutter_architecture: x64
            runner: windows-latest
          - build_architecture: arm64
            artifact_architecture: arm64
            flutter_architecture: x64
            runner: windows-11-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          architecture: ${{ matrix.flutter_architecture }}

      - name: Use ARM64 Dart host for Flutter
        if: matrix.build_architecture == 'arm64'
        run: .\scripts\setup_flutter_windows_arm64_host.ps1

      - name: Compile for Windows
        run: .\scripts\compile_windows_zip.ps1 -Architecture ${{ matrix.build_architecture }} -FlutterCommand flutter -OutputPath LocalSend.zip

      - name: Upload zip
        uses: actions/upload-artifact@v6
        with:
          name: windows-zip-${{ matrix.artifact_architecture }}-result
          path: app/LocalSend.zip
